Repository exercism/rexx, pull requests merged in 2024-07, with the labels that each got.

#117 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#118 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#119 resistor-color-trio: sync
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/tiny

#120 chore(verify-exercises): conditionally copy toplevel example from .meta
  bin/verify-exercises
Labels: x:type/coding, x:rep/small, x:action/fix, x:size/small

#121 fix(verify-exercises): copy 'example-toplevel.rexx' from .meta
  bin/verify-exercises
Labels: x:type/coding, x:size/tiny, x:module/test-runner, x:action/fix, x:rep/tiny

#122 chore(verify-exercises): skip tests for WIP exercises
  bin/verify-exercises
Labels: x:action/improve, x:type/coding, x:rep/small, x:module/test-runner, x:size/small

#125 fix(bob-check.rexx): rectify text change from previous bulk update
  exercises/practice/bob/bob-check.rexx
Labels: x:type/coding, x:rep/small, x:action/fix, x:size/small, x:module/practice-exercise

#126 refactor(*): refactor several exercises
  exercises/practice/gigasecond/gigasecond-check.rexx
  exercises/practice/grains/.meta/example.rexx
  exercises/practice/leap/.meta/config.json
Labels: x:action/improve, x:type/content, x:rep/medium, x:size/medium, x:module/practice-exercise

#129 refactor(bin/make-exercise): revise exercise creation script
  bin/make-exercise
Labels: enhancement, x:action/improve, x:rep/large, x:type/coding, x:type/docs, x:size/large

#131 refactor(accumulate,list-ops,strain): revise to support test functions
  exercises/practice/accumulate/.meta/example.rexx
  exercises/practice/accumulate/accumulate.rexx
  exercises/practice/accumulate/testlib/accumulate-funcs.rexx
  exercises/practice/list-ops/.meta/example.rexx
  exercises/practice/list-ops/list-ops.rexx
  exercises/practice/list-ops/testlib/list-ops-funcs.rexx
  exercises/practice/strain/.meta/example.rexx
  exercises/practice/strain/strain.rexx
  exercises/practice/strain/testlib/strain-funcs.rexx
Labels: enhancement, x:action/improve, x:type/coding, x:type/content, x:rep/medium, x:size/medium, x:module/practice-exercise

#132 refactor(bin/make-exercise): revise exercise creation script
  bin/make-exercise
Labels: x:action/improve, x:type/coding, x:rep/small, x:size/small

#133 refactor(bin/make-exercise): revise exercise creation script
  bin/make-exercise
Labels: x:action/improve, x:type/coding, x:rep/medium, x:size/medium

#134 refactor(bin/make-exercise): revise exercise creation script
  bin/make-exercise
Labels: x:action/improve, x:rep/large, x:type/coding, x:size/large
